# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20161020_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'To do'), (2, 'Work in progress'), (3, 'To review'), (4, 'Done'), (5, 'Wish')], default=5, max_length=20),
        ),
    ]
