# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20161023_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(choices=[(1, '#25a2a6'), (2, '#a4d05f'), (3, '#fddd62'), (4, '#f48f97')], default=1, max_length=7),
        ),
    ]
