# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_board_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(choices=[(1, 'b'), (2, 'g'), (3, 'y'), (4, 'r')], default=1, max_length=7),
        ),
    ]
