# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20161023_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(choices=[(1, 'blue'), (2, 'green'), (3, 'yellow'), (4, 'red')], default=1, max_length=7),
        ),
    ]
